ci: upgrade the misspell action
the older version is failed to pull some package,
upgrading to try if it dixes it

 2.282 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
  ------
  Dockerfile:5
  --------------------
     4 |
     5 | >>> RUN apt-get update \
     6 | >>>     && apt-get install -y --no-install-recommends \
     7 | >>>         ca-certificates \
     8 | >>>         git \
     9 | >>>         wget \
    10 | >>>     && apt-get clean \
    11 | >>>     && rm -rf /var/lib/apt/lists/*
    12 |
  --------------------
  ERROR: failed to build: failed to solve: process "/bin/sh -c apt-get update     && apt-get install -y --no-install-recommends         ca-certificates         git         wget     && apt-get clean     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 10

Signed-off-by: parth-gr <partharora1010@gmail.com>
(cherry picked from commit f51982685e54aba7f9d5314dd2f14792d315e515)