name required in helm command
As doc explains:
```
$ helm install --namespace rook-ceph rook-release/rook-ceph
Error: must either provide a name or specify --generate-name
```